#  sudo docker-compose up --build
#  sudo docker-compose up --build -d
#OR
#  sudo docker-compose down
#  sudo docker-compose up

version: '3'

services:
  web:
    container_name: centos_php72_apache_oci8_full
    build:
      context: ./Image_Repository
    ports:
        - 9010:80
    volumes:
      # CODE - PHP CODE VOLUMES
      - ./PHP Project/:/var/www/html/


      # CODE - TOMCAT DYNAMIC CONFIG
      - ./Tomcat Project/:/var/lib/tomcat/webapps/
      # OR
      #- ./Tomcat Project/:/opt/tomcat/webapps/


      # CONFIG - php.ini DYNAMIC CONFIG
      - ./Image_Repository/conf/php:/etc/php.d/


      # CONFIG - TOMCAT DYNAMIC CONFIG
      #- ./Image_Repository/conf/apache:/etc/httpd/conf/


      # CONFIG - APACHE DYNAMIC CONFIG
      #- ./Image_Repository/conf/apache:/etc/apache2/sites-enabled/
      #- ./Image_Repository/conf/apache:/etc/httpd/conf/

    tty: true









