#  sudo docker-compose up --build
#  sudo docker-compose up --build -d
#OR
#  sudo docker-compose down
#  sudo docker-compose up

version: '3'

services:
  web:
    container_name: centos_php72_apache_oci8_full
    build:
      context: ./Image_Repository
    ports:
      - 9020:80    #apache
      - 9080:8080  #tomcat
    volumes:
      # CODE - PHP CODE VOLUMES
      - ./PHP Project/:/var/www/html/


      # CODE - TOMCAT DYNAMIC CONFIG
      - ./Tomcat Project/:/var/lib/tomcat/webapps/
      # OR
      #- ./Tomcat Project/:/opt/tomcat/webapps/

    tty: true



