#  sudo docker-compose up --build
#  sudo docker-compose up --build -d
#OR
#  sudo docker-compose down
#  sudo docker-compose up

version: '3'

services:
  web:
    container_name: centos_php72_apache_oci8_full
    build:
      context: ./docker
    ports:
        - 9010:80
    volumes:
      # PHP CODE VOLUMES
      - ./PHP Project/:/var/www/html/

      # TOMCAT DYNAMIC CONFIG
      - ./Tomcat Project/:/var/lib/tomcat/webapps/
      # OR
      #- ./Tomcat Project/:/opt/tomcat/webapps/

      # php.ini DYNAMIC CONFIG
      - ./docker/conf/php:/etc/php.d/

      # APACHE DYNAMIC CONFIG
      #- ./docker/conf/apache:/etc/apache2/sites-enabled/
      #- ./docker/conf/apache:/etc/httpd/conf/

      # TOMCAT DYNAMIC CONFIG
      #- ./docker/conf/apache:/etc/httpd/conf/

    tty: true









